---
title: "About This Website"
---

This website provides community-contributed translations of the project-wide Code of Conduct statement for [Bioconductor](https://bioconductor.org/), originally written in [English, United States](en-US.html). 

### Contributors (by language, alphabetical)

#### `r emo::ji("China")` Chinese, China

- **Maintainer:** [Xueyi Dong](https://github.com/XueyiDong)

#### `r emo::ji("United_States")` English, United States

- [BioC 2020 Organizing committee](https://bioc2020.bioconductor.org/organizers)
- **Maintainer:** [Bioconductor Code of Conduct Committee](https://www.bioconductor.org/about/code-of-conduct/)

#### `r emo::ji("France")` Français, France

- **Maintainer:** [Kevin Rue-Albrecht](https://github.com/kevinrue)

#### `r emo::ji("Germany")` German, Germany

- **Maintainer:** [Helena L. Crowell](https://github.com/HelenaLC)
- [Lukas M. Weber](https://github.com/lmweber)

#### `r emo::ji("India")` Hindi, India

n/a

#### `r emo::ji("Italy")` Italiano, Italia

- **Maintainer:** [Dario Righelli](https://github.com/drighelli)

#### `r emo::ji("Japan")` Japanese, Japan

- [Kozo Nishida](https://github.com/kozo2)

#### `r emo::ji("Brazil")` Portuguese, Brazil

- **Maintainer:** [Daniela Cassol](https://github.com/dcassol)

#### `r emo::ji("Russia")` Russian, Russian Federation

- [Mikhail Dozmorov](https://github.com/mdozmorov)

#### `r emo::ji("Spain")` Spanish, Spain

- **Maintainer:** [Robert Castelo](https://github.com/rcastelo)
- [Lluís Revilla](https://github.com/llrs)
- [Mireia Ramos-Rodríguez](https://github.com/mireia-bioinfo)
- [Estefania Mancini](https://github.com/estepi)
