---
title: "`r emo::ji('Spain')` Declaración del Código de Conducta del Proyecto Bioconductor (Español, España)"
---

(Adaptado del [BioC 2020 Code of Conduct][1])

# Código de Conducta

## Versión 1.2.0 (25 de noviembre del 2022)

_Código de Conducta inicial del proyecto, ampliado a partir de documentos previos elaborados específicamente para conferencias_

La comunidad Bioconductor valora un acercamiento abierto a la ciencia que promueve

* compartir ideas, código, software y conocimientos
* colaboración
* diversidad e inclusión
* un entorno amable y acogedor
* contribuciones de la comunidad

En línea con estos valores, el proyecto Bioconductor tiene por objetivo proporcionar una experiencia acogedora, alentadora y respetuosa, libre de acoso, intimidación y abuso, independientemente de:

* la identidad: género, identidad y expresión de género, orientación sexual, discapacidad, apariencia física, etnia, complexión física, raza, edad, religión, idioma, etc.
* la posición intelectual: aproximaciones al análisis de datos, preferencias de software, estilo de programación, perspectiva científica, etapa profesional, etc.

La participación en esta comunidad implica el compromiso de no tomar parte en comportamientos contrarios a estos valores en ningún evento (en persona o virtual, incluyendo pero no limitado a charlas, talleres, sesiones de póster, actividades sociales), canales de comunicación electrónicos (incluyendo pero no limitado al Slack comunity-bioc, el sitio web de soporte al usuario, foros online, la revisión de paquetes y comunicaciones en medios sociales) o paquetes de software (incluyendo los mensajes de confirmación de Git) auspiciados por Bioconductor.
Además, requerimos a todos los participantes utilizar cuentas identificables en los foros online de Bioconductor. 
Las cuentas que no se adhieran a este requisito después de una solicitud para desanonimizarlas pueden ser eliminadas.

No toleramos el acoso, la indimidación, o el abuso de miembros de la comunidad.
El lenguaje y la iconografía sexuales no son apropiados en presentaciones, comunicaciones o plataformas online, incluyendo chats.

Cualquier persona que viole el Código de Conducta puede ser sancionada o expulsada temporal o permanentemente de una plataforma electrónica o evento a discreción del Comité del Código de Conducta.


#### _Ejemplos de comportamientos inaceptables de acoso, intimidación y abuso_

El acoso incluye, pero no está limitado a:

* Hacer comentarios en chats, a una audiencia o de forma personal, que degraden o menosprecien a otra persona
* Compartir imágenes sexuales online
* Fotografias o grabaciones que representen acoso
* Disrupción sostenida de charlas u otros eventos
* Atención sexual no deseada
* Promover o alentar cualquiera de los comportamientos anteriores

La intimidación y el abuso incluyen, pero no están limitados a:

* Comportamientos agresivos o intimidatorios
* Insultar o burlarse del intelecto, trabajo, perspectiva o pregunta/comentario de otra persona
* Hacer referencia al género, identidad y expresión de género, orientación sexual, discapacidad, apariencia física, complexión física, raza, edad, religión, u otros atributos personales de alguien en el contexto de una discusión científica
* Hacer sentir a alguien que no es bienvenido de forma deliberada
* Comportamiento ofensivo (mensajes ofensivos o con intención de provocar)
* Publicación continua de mensajes sin relación al tema

## Aplicación

Se espera que cualquier persona a quien se le pida cesar un comportamiento intimidatorio o de acoso lo cumpla inmediatamente.

Si una persona contraviene el Código de Conducta, el Comité del Código de Conducta se reserva el derecho a actuar de la forma que asegure un entorno acogedor para todos los miembros de la comunidad.
Esto incluye advertir o expulsar al presunto infractor, temporal o permanentemente, del evento y/o plataformas electrónicas bajo el control de Bioconductor.

El comité del Código de Conducta puede tomar decisiones para remediar cualquier situación diseñada para,
o con el claro impacto de, dañar un evento o plataforma de comunicación electrónica o hacer el entorno
hostil para cualquier miembro de la comunidad.

Esperamos que todo el mundo en la comunidad Bioconductor cumpla con el Código de Conducta cuando participa en eventos y plataformas de comunicación online de Bioconductor.

## Denuncias

Si alguien te hace a ti, o a cualquier otra persona, sentir inseguro o no bienvenido, por favor denúncialo tan pronto como sea posible. 
Puedes denunciar de forma anónima o personalmente. 
Todas las denuncias serán revisadas por el Comité del Código de Conducta y serán gestionadas de forma confidencial.

#### _Electrónicamente_

Puedes hacer una denuncia anónima o no-anónima a través del siguiente enlace: <https://forms.gle/gEWHBWnXvZbEdFsq5>.
Esta página contiene una caja de texto libre que será re-enviada al Comité del Código de Conducta.
Alternativamente, puedes enviar un mensaje por correo electrónico al Comité del Código de Conducta
(<code-of-conduct@bioconductor.org>). Si te sientes incómodo denunciando ante el Comité del Código de Conducta como grupo,
puedes contactar con cualquier miembro del comité por correo electrónico o a través de un mensaje directo en el canal
de Slack community-bioc. Por favor, incluye capturas de pantalla o copias de todas las conversaciones electrónicas relevantes siempre que sea posible (no hace falta que comprometas tu anonimidad!).

No podemos hacer un seguimiento de una denuncia anónima directamente contigo, pero la investigaremos a fondo y tomaremos la decisión que sea necesaria para prevenir que vuelva a ocurrir.

#### _Personalmente (en cualquier evento Bioconductor: en persona o virtual)_

Puedes formular una denuncia personalmente ante cualquier miembro del Comité del Código de Conducta presente en un evento.

Cuando recibimos una denuncia personalmente, nos aseguraremos de que lo hacemos en un entorno seguro que evite que pueda ser escuchada.
En algunos casos necesitaremos involucrar personal adicional del evento para garantizar que la denuncia sea gestionada apropiadamente.
Una vez en un entorno seguro, te pediremos que nos cuentes qué ha pasado.
Sabemos que este proceso puede resultar incómodo, por lo que lo gestionaremos de la forma más respetuosa posible y puedes traer un acompañante que te dé apoyo.
No se te pedirá confrontar a nadie, y no le diremos a nadie quién eres.

Nuestro equipo estará encantado de ayudarte a encontrar el apoyo oportuno (por ejemplo, ayudándote a contactar con la seguridad del hotel/sede del evento, autoridades locales de orden público, servicios de apoyo locales, proporcionar escolta, o en cualquier otro caso ayudarte a sentirte segura o seguro durante el evento).

Apreciamos tu asistencia y participación en eventos de Bioconductor y en nuestra comunidad.

#### _Mediador_

Entendemos que puedas preferir que la persona que supervisa la resolución de tu conflicto no esté relacionada con Bioconductor. Para facilitarlo, el Comité del Código de Conducta nombrarà un mediador, o mediadora, de otra comunidad de código abierto y distinta de los miembros del proyecto Bioconductor. Si bien el mediador no tiene la capacidad para establecer, cambiar or descartar las decisiones alcanzadas por el Comité del Código de Conducta, puede asistir los miembros de la comunidad ofreciendo consejo, mediación, orientación y referencias a otros recursos. El mediador puede ser contactado directamente por email (ver más abajo) para asegurar un proceso confidencial, imparcial, informal e independiente.

#### _Procedimiento de incidente_

El Comité del Código de Conducta sigue un procedimiento estándard para tratar conflictos.
Este procedimiento está resumido brevemente
[aquí](https://bioconductor.github.io/CodeOfConduct/incident_response.html). Los procedimientos
de incidentes están basados en el libro "How to respond to Code of Conduct Reports" de Valerie Aurora y Mary Gardiner.

### Comité del Código de Conducta

* (Chair) Saskia Freytag <sas.freytag@gmail.com> (hasta 2023) ella [EN, DE]
* Laurent Gatto <laurent.gatto@gmail.com> (hasta 2023) él [FR, EN] (TAB, European Bioconductor Society)
* Martín Dávila-Cervantes aldntmi@gmail.com (until 2025) él [EN, FR, ES]
* Federica Gazzelloni fede.gazzelloni@gmail.com (until 2025) ella [IT,EN]
* Gerry Tonkin-Hill g.tonkinhill@gmail.com (until 2025) él [EN]
* Michael Love <michaelisaiahlove@gmail.com> (hasta 2024) él [EN] (TAB)
* Federico Marini <fede.maro@gmail.com> (hasta 2024) él [EN, IT, DE]
* Sowmya Parthiban <sowmyaparthiban@gmail.com> (hasta 2024) ella [EN, Tamil]
* Shixiang Wang wangshx@shanghaitech.edu.cn (until 2025) él [CN,EN]
* Anna Quaglieri <anna.quaglieri16@gmail.com> (hasta 2024) ella [EN, IT]
* Lluís Revilla <lluis.revilla@gmail.com> (hasta 2024) él [CA, ES, EN]
* Kevin Rue-Albrecht kevinrue67@gmail.com  (until 2024) él [FR, EN] (CAB)
* (Mediadora) Michelle Savage michellesavage.galaxy@gmail.com (Galaxy project) ella [ES,EN]

[1]: https://bioc2020.bioconductor.org/code_of_conduct
