---
title: "`r emo::ji('France')` Code de bonne conduite applicable à l'intégralité du projet Bioconductor (Français, France)"
---

(Adapté du [Code de bonne conduite pour la conférence BioC 2020][1], traduit de l'[Anglais, Américain](en-US.html))

# Code de bonne conduite

**Version 1.2.0 (25 November 2022)**

_Version initiale du Code de Bonne Conduite applicable à l’intégralité du projet Bioconductor, étendu sur la base de documents rédigés spécifiquement pour des conférences antérieures_

La communauté Bioconductor valorise
une approche ouverte aux sciences favorisant:

* l'échange d’idées, de code, de logiciel, et d’expertise
* collaboration
* diversité et inclusion
* un environnement accueillant et chaleureux
* contributions de la communauté

Conformément à ces valeurs, Bioconductor se consacre à fournir une expérience accueillante, solidaire, collégiale, sans harcèlement, intimidation et intimidation, indépendamment de:

* identité: genre, identité et expression du genre, orientation sexuelle, handicap, apparence physique, ethnicité, taille, race, âge, religion, langage, etc.
* intellectual position: approaches to data analysis, software preferences, coding style, scientific perspective, stade de carrière, etc.

En participant à cette communauté, vous acceptez de ne pas adopter un comportement contraire à ces valeurs lors de tout événement parrainé par Bioconductor (en personne ou virtuel, y compris, mais sans s'y limiter, conférences, séminaires, presentations de posters, activités sociales), dans tout canal de communication électronique (y compris, mais sans s'y limiter, l'espace de travail Slack \"community-bioc\", le site de support, les forums en ligne, le site de revue de packages, et les communications sur les médias sociaux), ou dans tout package (y compris les commits). De plus, nous demandons à tous les participants de posséder des comptes identifiables sur les forums en ligne de Bioconductor.

Nous ne tolérons pas le harcèlement, l'intimidation ou la persécution des membres de la communauté. Le langage sexuel et l'imagerie sont inappropriés dans les présentations, les communications, ou les sites en ligne, y compris les discussions en ligne.

Toute personne qui enfreint le Code de conduite peut être sanctionnée ou expulsée temporairement ou définitivement d'une plate-forme électronique ou d'un événement à la discrétion du comité du code de conduite.

#### _Exemples de harcèlement, d'intimidation et de comportements inacceptables_

Le harcèlement inclut, mais ne se limite pas à :

* Faire des commentaires dans les discussions en ligne, publiquement ou personnellement, qui déprécient ou dévalorisent une autre personne
* Partager des images sexuelles en ligne
* Harceler par le biais de photographie ou d'enregistrement
* Interrompre de façon prolongée des présentations ou autres événements
* Des avances sexuelle indésirables
* Défendre ou encourager l'un des comportements ci-dessus

L'intimidation et la persécution incluent, mais ne sont pas limitées à:

* Un comportement agressif ou intimidant
* Se moquer ou insulter l'intelligence, le travail, la perspective, la question ou le commentaire d'une autre personne
* Faire référence au sexe, à l’identité et à l’expression de genre, à l'orientation sexuelle, au handicap, à l’apparence physique, la taille, la race, l'âge, la religion ou d'autres attributs personnels dans le contexte d'une discussion scientifique
* Délibérément faire quelqu'un se sentir rejeté
* Un comportement de "trolling" (envoi de messages délibérément inflammatoires ou offensifs)
* L'envoi continu de messages hors-sujet

### Mise en application
Toute personne invitée à cesser un comportement de harcèlement ou d'intimidation devrait se conformer immédiatement aux instructions reçues.

Si une personne contrevient au Code de conduite, le comité du Code de conduite se réserve le droit de prendre des mesures qui garantissent un environnement accueillant pour tous les membres de la communauté. Cela inclut l'avertissement du délinquant présumé ou son expulsion temporaire ou permanente de l'événement et/ou des plateformes électroniques sous le contrôle de Bioconductor.

Le comité du code de bonne conduite peut prendre des mesures pour réparer toute action visant à, ou causant clairement, la perturbation d'un événement ou d'une plateforme de communication électronique, ou rendant l'environnement hostile à tout membre de la communauté.

Nous demandons à tous les membres de la communauté Bioconductor de se conformer au Code de bonne conduite lorsqu'ils participent aux événements Bioconductor et aux plateformes de communication en ligne.

## Signalement
Si quelqu'un vous fait sentir en danger ou indésirable, veuillez le signaler dès que possible. Vous pouvez remplir le formulaire de signalement de façon anonyme ou signé de votre nom. Tous les signalements seront examinés par le Comité du Code de bonne conduite et resteront confidentiels.

#### _Electroniquement_

Vous pouvez faire un rapport anonyme ou signé de votre nom via le lien suivant: <https://forms.gle/gEWHBWnXvZbEdFsq5>. Il s'agit d'une boîte de texte en forme libre qui sera transmise au comité du code de bonne conduite. Alternativement, vous pouvez envoyer un courriel au Comité du Code de bonne conduite (<code-of-conduct@bioconductor.org>). Si vous n'êtes pas confortable à l'idée de contacter l'ensemble du comité du code de conduite, vous pouvez contacter n'importe quel membre du comité par courriel ou un message direct sur l'espace de travail Slack "community-bioc". Veuillez inclure des captures d'écran/copies de toutes les conversations électroniques pertinentes dans la mesure du possible (vous n'avez pas besoin de compromettre votre anonymat!).

Nous ne pouvons pas suivre un signalement anonyme directement avec vous, mais nous examinerons le signalement en profondeur et prendrons toutes les mesures nécessaires pour éviter une récidive.

#### _Signalement direct (pour tout événement Bioconductor: en personne ou virtuel)_

Vous pouvez faire un signalement directement à tout membre du comité du Code de bonne conduite présents à un événement.

Lorsque nous prenons un rapport direct, nous nous assurerons que vous êtes en sécurité et que personne d'autre ne peut épier la conversation. Il se peut que nous fassions appel à un autre personnel de l’évènement pour nous assurer que votre rapport est géré correctement. Une fois en sécurité, nous vous demanderons de nous faire part de ce qui s'est passé. Cela peut être bouleversant, mais nous traiterons toute information avec le plus grand respect possible, et vous pouvez vous accompagner de quelqu'un pour vous soutenir. On ne vous demandera pas de confronter qui que ce soit, et nous ne dirons à personne qui vous êtes.

Notre équipe se fera un devoir de vous aider à obtenir le soutien approprié (par exemple, aide à contacter la sécurité de l'hôtel/du lieu, les forces de l'ordre locales, les services de soutien locaux, escorte, ou tout support pour vous sentir en sécurité pendant la durée de l'événement).

Nous apprécions votre présence et votre participation aux événements Bioconductor et à notre communauté.

#### Médiation

Nous comprenons que vous voudrez peut-être voir la résolution de votre conflit gérée par une personne non liée à Bioconductor. Pour faciliter ceci, le comité du Code de bonne conduite nomme un médiateur (une médiatrice) associée à une autre communauté open source. Sans avoir la capacité d'établir, de changer, ou d'annuler les décisions prises par le comité du Code de bonne conduite, leur rôle leur permet d'aider les membres du comité par le biais de consultation, médiation, coaching, et références à d'autres ressources. Le médiateur (la médiatrice) peut être contacté(e) directement par email (voir ci-dessous) pour garantir un processus confidentiel, impartial, informel, et indépendent.

#### Procédure en cas d'incident

Le comité du Code de bonne conduite suit une procédure standardisée pour gérer les conflits.
Cette procédure est brièvement résumée [ici](https://bioconductor.github.io/CodeOfConduct/incident_response.html). Les procédures en cas d'incident sont basées sur le livre "How to Respond to Code of Conduct Reports", co-écrit par Valerie Aurora et Mary Gardiner.


### Comité de bonne conduite

* (Chair) Saskia Freytag <sas.freytag@gmail.com> (jusqu'en 2023) elle/elle [EN, DE]
* Laurent Gatto <laurent.gatto@gmail.com> (jusqu'en 2023) il/lui [FR, EN] (TAB, European Bioconductor Society)
* Martín Dávila-Cervantes <aldntmi@gmail.com> (jusqu'en 2025) il/lui [EN, FR, ES]
* Federica Gazzelloni <fede.gazzelloni@gmail.com> (jusqu'en 2025) elle/elle [IT, EN]
* Gerry Tonkin-Hill <g.tonkinhill@gmail.com> (jusqu'en 2025) il/lui [EN]
* Michael Love <michaelisaiahlove@gmail.com> (jusqu'en 2024) il/lui [EN] (TAB)
* Federico Marini <fede.maro@gmail.com> (jusqu'en 2024) il/lui [EN, IT, DE]
* Sowmya Parthiban <sowmyaparthiban@gmail.com> (jusqu'en 2024) il/lui [EN, Tamil]
* Shixiang Wang wangshx@shanghaitech.edu.cn (jusqu'en 2025) il/lui [CN, EN]
* Anna Quaglieri <anna.quaglieri16@gmail.com> (jusqu'en 2024) elle/elle [EN, IT]
* Lluís Revilla <lluis.revilla@gmail.com> (jusqu'en 2024) il/lui[CAT, ES, EN]
* Kevin Rue-Albrecht <kevinrue67@gmail.com> (jusqu'en 2024) il/lui [FR, EN] (CAB)
* (Médiatrice) Michelle Savage <michellesavage.galaxy@gmail.com> (Projet Galaxy) elle/elle [ES, EN]

* Yagoub Adam <yagoub@alumni.usp.br> (jusqu'en 2022)
[1]: https://bioc2020.bioconductor.org/code_of_conduct
