---
title: "Project-wide Code of Conduct statement for Bioconductor"
---

Welcome to the [_Bioconductor_](https://bioconductor.org/) community!

## Purpose

This website hosts the official English version of the project-wide Code of
Conduct statement for the [_Bioconductor_](https://bioconductor.org/) project -
maintained by the _Bioconductor_ Code of Conduct committee - as well as
translations contributed by volunteer community members.

These living documents are intended for reference and use during
[_Bioconductor_](https://bioconductor.org/) in-person events (e.g., conferences)
and online communications (e.g., [Slack workspace][bioc-slack],
[support forum][bioc-support-forum]).
Organisers and moderators are encouraged to feature a prominent link to these
documents (including version number) on the website or online platform
associated with the relevant [_Bioconductor_](https://bioconductor.org/) events
and communications.

In case of conflict or out-of-date translations, the
[latest English version](en-US.html)) rules.

To contribute new translations or updates, please read the
[contributing guidelines](contribute.html).

## Languages (alphabetical)

|          Flag           | Language       | Version | Link               |
| :---------------------: | :------------- | :-----: | :------------------|
| `r emo::ji("China")` | Chinese, China | 1.0.2 | [zh-CN](zh-CN.html) |
| `r emo::ji("United_States")` | **English, United States (original version)** | 1.0.2 | [en-US](en-US.html) |
| `r emo::ji("France")` | French, France | 1.0.2 | [fr-FR](fr-FR.html) |
| `r emo::ji("Germany")` | German, Germany | 1.0.2 | [de-DE](de-DE.html) |
| `r emo::ji("India")` | Hindi, India | - | [hi-IN](hi-IN.html) |
| `r emo::ji("Italy")` | Italian, Italy | 1.0.2 | [it-IT](it-IT.html) |
| `r emo::ji("Japan")` | Japanese, Japan | 1.0.2 | [jp-JP](jp-JP.html) |
| `r emo::ji("Brazil")` | Portuguese, Brazil | 1.0.1 | [pt-BR](pt-BR.html) |
| `r emo::ji("Russia")` | Russian, Russian Federation | 1.0.2 | [ru-RU](ru-RU.html) |
| `r emo::ji("Spain")` | Spanish, Spain | 1.0.2 | [es-ES](es-ES.html) |

## Code of Conduct (English, United States)

This is the latest version of the original project-wide Code of Conduct statement for Bioconductor.
Linked from [en-US](en-US.html).

```{r, child='en-US.Rmd'}
```

[bioc-slack]: https://bioc-community.herokuapp.com/
[bioc-support-forum]: https://support.bioconductor.org/
