---
title: "`r emo::ji('Italy')` Project-wide Codice di Comportamento per Bioconductor (Italiano, Italia)"
---

(Adattato dal [Codice di Comportamento per la conferenza BioC 2020][1], tradotto dall'[Inglese, Americano](en-US.html))

# Codice di Comportamento

## Versione 1.3.0 (12 Gennaio, 2024)

_Codice di Comportamento iniziale, esteso dai precedenti documenti specificamente redatti per le conferenze precedenti._


I valori della Comunità di Bioconductor comprendono un approccio aperto alla scienza che promuove

* la condivisione di idee, codice software ed esperienze
* collaborazione
* diversità ed inclusività 
* un ambiente caloroso e accogliente
* contributi alla comunità

In linea con questi valori, Bioconductor si dedica a creare una comunità accogliente, solidale, un'esperienza collegiale assente da molestie, intimidazioni e bullismo indipendentemente da:

* identità: genere, identità e espressione di genere, orientamento sessuale, disabilità, apparenza fisica, etnia, corporatura, età, religione, lingua, ecc.
* opinioni intellettuali: approcci all'analisi dati, preferenze nella scelta di software, stile del codice, posizioni scientifiche, fase della carriera, ecc.

Partecipando a questa comunità, acconsenti a non avere comportamenti contrari a questi valori ad ogni evento sponsorizzato da Bioconductor (in presenza o virtuale, inclusi, ma non limitatatamente a presentazioni, workshops, sessioni poster, attività sociali), canali di comunicazione elettronica (inclusi, ma non limitatamente al community-bioc [Slack] (https://slack.bioconductor.org/), il sito di supporto, i forum online, il sito per il referaggio dei pacchetti e le comunicazioni sui social media), o pacchetti (commit inclusi).

Inoltre, richiediamo a tutti i partecipanti di avere account identificabili nei forum online di Bioconductor. Gli account che non aderiscono a ciò dopo la richiesta di de-anonimizzazione potranno essere cancellati. 

Non tolleriamo molestie, intimidazioni, o bullismo dei membri della comunità.
Linguaggio e immagini a sfondo sessuale non sono appropriate nelle presentazioni, comunicazioni o siti online, incluse le chat.

Chiunque violi il Codice di Comportamento può essere sanzionato o espulso temporaneamente o permanentemente dalla piattaforma elettronica o da un evento a discrezione della Commissione del Codice di Comportamento.

La comunità di Bioconductor è impegnata a collaborazioni etiche e ad evitare collaborazioni con entità i cui comportamenti sono inconsistenti con i valori di Bioconductor.
Incoraggiamo i membri della comunità a riportare o a sollevare preoccupazioni che ritengono non etiche alla commissione del Codice di Comportamento tramite il modulo di segnalazione.

#### _Esempi inaccettabili di comportamento denigratorio, molesto, intimidatorio, e bullismo_

La molestia include, ma non si limita a:

* Fare commenti in chat, di gruppo o individualmente, al fine di sminuire o umiliare un'altra persona
* Condividere online immagini a sfondo sessuale
* Fotografie o registrazioni indesiderate
* Interruzione prolungata di presentazioni o altri eventi
* Sgradite/indesiderate attenzioni sessuali
* Sostenere o incoraggiare uno o più comportamenti qui descritti

Intimidazione e bullismo includono, ma non sono limitati a:

* Comportamenti aggressivi o intimidatori
* Deridere o insultare intelletto, lavoro, prospettive o domande/commenti di un'altra persona
* Deridere il genere, l'identità e l'espressione di genere, l'orientamento sessuale, le disabilità, l'apparenza fisica, la corporatura, l'età, la religione, o qualasiasi altro attributo nel contesto di una discussione scientifica
* Far sentire deliberatamente una persona non benvenuta
* Comportamenti di \"trolling\" (messaggi intenzionalmente provocatori o offensivi)
* Il continuo invio di messaggi fuori dal contesto


## Messa in atto

Ci si aspetta che chiunque riceva la richiesta di fermare un comportamento discriminatorio, molesto o intimidatorio la soddisfi immediatamente.

Se una o più persone contravvengono al Codice di Comportamento, la Commissione del Codice di Comportamento si ritiene in diritto di agire in qualunque modo al fine di assicurare un ambiente confortevole per tutti i membri della comunità.
Questo include l'avvertire il presunto colpevole o l'espulsione temporanea/permanente dall'evento e/o dalle piattaforme elettroniche sotto il controllo di Bioconductor.

La Commissione del Codice di Comportamento può agire in modo da porre rimedio a qulasiasi cosa progettata per, o con il chiaro impatto di, disturbare un evento o una piattaforma di comunicazione elettronica o da rendere l'ambiente ostile per qualsiasi membro della comunità.

Ci aspettiamo che ogni membro della comunità di Bioconductor si attenga al Codice di Comportamento durante la partecipazione agli eventi di Bioconductor e sulle piattaforme elettroniche online.

## Segnalazione

Se qualcuno fa sentire te o chiunque altro non al sicuro o non benvenuto, sei pregato di riportarlo il prima possibile. 
La segnalazione può essere sia in forma anonima che personale. 
Tutte le segnalazioni saranno valutate dalla Commissione del Codice di Comportamento e verranno trattate in maniera confidenziale.

#### _Segnalazione per via Elettronica_

Puoi fare una segnalazione anonima o non-anonima al seguente link [https://forms.gle/gEWHBWnXvZbEdFsq5](https://forms.gle/gEWHBWnXvZbEdFsq5) 
dove è presente un box di testo in formato libero che verrà inviato alla Commissione del Codice di Comportamento.
In alternativa puoi inviare una email alla Commissione del Codice di Comportamento (code-of-conduct@bioconductor.org).
Se non ti senti a tuo agio a fare una segnalazione all'intera Commissione del Codice di Comportamento, puoi contattare individualmente un qualsiasi membro della Commissione del Codice di Comportamento tramite email o con un messaggio privato sul canale Slack \"community-bioc\". Per favore includi \"screenshots\"/copie di tutte le conversazioni rilevanti ogni volta possibile (non c'è bisogno di compromettere il tuo anonimato!).

Non possiamo ricontattarti in maniera diretta a seguito di una segnalazione anonima, ma la investigheremo appieno e prenderemo provvedimenti ogni qualvolta sarà necessario al fine di prevenire una recidiva.

#### _Segnalazione Personale (per ogni evento Bioconductor: in persona o virtuale)_

Puoi effettuare una segnalazione ad ogni membro della Commissione del Codice di Comportamento presente a un evento.

Quando viene fatta una segnalazione personale, ci occuperemo personalmente di farti sentire al sicuro e che la tua segnalazione non sia origliata.
Potremmo coinvolgere altri membri dello staff al fine di assicurare che la tua segnalazione sia trattata in maniera opportuna.
Una volta al sicuro, ascolteremo ciò che hai da riportare su ciò che è successo.
Per quanto possa risultare emozionalmente difficile, tratteremo la tua segnalazione nel modo più rispettoso possibile, e potrai portare qualcuno a tuo supporto.
Non ti verrà chiesto di confrontarti con nessuno, e non diremo a nessuno chi sei.

Il nostro gruppo sarà felice di aiutarti e di offrirti il supporto necessario (ad esempio aiutarti a contattare hotel o altri luoghi sicuri, forze dell'ordine locali, servizi di supporto locali, fornire accompagnatori, o altrimenti assisterti per farti sentire al sicuro durante la durata dell'evento).

Diamo valore alla tua presenza e partecipazione agli eventi di Bioconductor e alla nostra comunità.

#### _Mediatore/Mediatrice_

Capiamo che tu possa volere una persona non collegata a Bioconductor che supervisioni la risoluzione del tuo conflitto. Per facilitare ciò, la Commissione del Codice di Comportamento nominerà un/una mediatore/mediatrice da una comunità open-source differente rispetto ai membri del progetto di Bioconductor. Seppur non avendo l'autorità di stabilire, cambiare o impostare decisioni prese dalla Commissione del Codice di Comportamento, possono assistere i membri della comunità offrendo loro consultazione, mediazione, istruzione e riferimenti ad altre risorse. Il/La mediatore/mediatrice può essere contattato/a direttamente via mail per assicurare un processo confidenziale, imparziale, informale e indipendente.

#### _Procedura dell'incidente_

La Commissione del Codice di Comportamento segue una procedura standard per trattare i conflitti.
Questa procedura è spigata brevemente [qui](https://bioconductor.github.io/CodeOfConduct/incident_response.html). Le procedure d'incidente sono basate sul libro "How to Respond to Code of Conduct Reports" di Valerie Aurora e Mary Gardiner.

###  Commissione del Codice di Comportamento

* (Co-Presidente) Anna Quaglieri anna.quaglieri16@gmail.com (until 2024) she/her [EN, IT]
* (Co-Presidente) Gerry Tonkin-Hill g.tonkinhill@gmail.com (until 2025) he/him [EN]
* Martín Dávila-Cervantes aldntmi@gmail.com (until 2025) he/him [EN, FR, ES] 
* Federica Gazzelloni fede.gazzelloni@gmail.com (until 2025) she/her [IT,EN]
* Michael Love michaelisaiahlove@gmail.com (until 2024) he/him [EN] (TAB)
* Federico Marini fede.maro@gmail.com (until 2024) he/him [EN, IT, DE]
* Sowmya Parthiban sowmyaparthiban@gmail.com (until 2024) she/her [EN, Tamil]
* Shixiang Wang wangshx@shanghaitech.edu.cn (until 2025) he/him [CN, EN]
* Lluís Revilla lluis.revilla@gmail.com (until 2024) he/him [CAT, ES, EN]
* Kevin Rue-Albrecht kevinrue67@gmail.com  (until 2024) he/him [FR, EN] (CAB)
* Paulina Boadiwaa Mensah pabbyboadiwaa@gmail.com (until 2025) she/her [EN, Akan]
* Peace Sandy peacesandy04@gmail.com she/her (until 2025) [EN]
* Sinmisoluwa Adesanya adesanyasinmisoluwa@gmail.com she/her (until 2025) [EN, Yoruba]
* (Mediatrice) Michelle Savage michellesavage.galaxy@gmail.com (Galaxy project) she/her [ES,EN]

[1]: https://bioc2020.bioconductor.org/code_of_conduct
