---
title: "`r emo::ji('Japan')` Project-wide Code of Conduct statement for Bioconductor (Japanese, Japan)"
---

([BioC 2020 の行動規範] から改作[1]、 [英語](en-US.html) から翻訳)

# 行動規範

**バージョン1.0.2 (2021年7月27日)**

_これは、以前に開催したカンファレンス固有のドキュメントから拡張されたプロジェクト全体の最初の行動規範です_


Bioconductor のコミュニティは下記を促進する科学へのオープンなアプローチを大切にしています。

* アイデア、コード、ソフトウェア、専門知識の共有
* コラボレーション
* 多様性と(人種や性別などにかかわらず)あらゆる人を受け入れようとすること
* 親切で居心地の良い環境
* コミュニティへの貢献

これらの価値観に沿って、Bioconductor は、下記に関係無く、「嫌がらせ、脅迫、いじめ」の無い、「歓迎的で、協力的で、それぞれが平等に権限を有する」体験を提供することに専念しています:

* 身元: 性別、性同一性や表現、性的指向、身体障害、容貌、民族性、体の大きさ、人種、年齢、宗教、言語 等。
* 知的地位：データ分析へのアプローチ、ソフトウェアの好み、コーディングスタイル、科学的視点、キャリアの段階 等。

このコミュニティに参加することにより、Bioconductor が主催する (直接会うまたはバーチャルのトーク、ワークショップ、ポスターセッション、ソーシャルアクティビティを含むがこれらに限定されない) イベントまたは (community-bioc Slack、サポートサイト、オンラインフォーラム、パッケージレビューサイトそしてソーシャルメディアコミュニケーションを含むがこれらに限定されない) 電子的なコミュニケーションチャンネルでこれらの価値観に反する行動をとらないことに同意するものとします。

我々はコミュニティメンバーへの嫌がらせ、脅迫、いじめを容認しません。
性的な言葉や画像は、プレゼンテーション、コミュニケーション、またはチャットを含むオンラインの場でふさわしくありません。

行動規範に違反する人は、行動規範委員会の裁量により、一時的または恒久的に電子的なプラットフォームまたはイベントから制裁または追放される場合があります。

#### _容認できない嫌がらせ、脅迫、いじめ行為の例_

ハラスメントには以下が含まれますが、これらに限定されません:

* チャットで次のようなコメントをする。聴衆に、または個人的に、他の人を軽蔑したり侮辱したりすること
* 性的な画像をオンラインで共有すること
* 嫌がらせの写真や記録
* 話し合いやその他のイベントのしつこい妨害
* 歓迎されない性的注意
* 上記の行動のいずれかを支持または奨励すること

脅迫やいじめには以下が含まれますが、これらに限定されません:

* 攻撃的なまたは威嚇するような行動
* 次をあざ笑うまたは侮辱すること。他人の知性、仕事、視点、または質問・コメント
* 次に言及すること。誰かの性別、性同一性や表現、性的指向、身体障害、容貌、体の大きさ、人種、年齢、宗教、または科学的議論の文脈でのその他の個人的属性
* 故意に誰かを歓迎されていないと感じさせること
* 荒らし行為 (故意に怒りをかき立てたり攻撃的なメッセージを行うこと)
* しつこい主題からずれた投稿


## 執行

嫌がらせや脅迫的な行動をやめるように求められた人は、すぐに従うように要求されます。

行動規範に違反した場合、行動規範委員会は、すべてのコミュニティメンバーのために快適な環境を保証する行動を取る権利を保持します。
これには、Bioconductor の管理下にあるイベント・電子プラットフォームからの違反被疑者の一時的・恒久的な除籍の警告が含まれます。

行動規範委員会は「イベントや電子通信プラットフォームを混乱させたり、コミュニティメンバーにとって環境を敵対的にしたりする」ように意図されたまたは明確な影響を与えるものを是正するための措置を講じることがあります。

我々は Bioconductor のコミュニティのすべての人が、Bioconductor のイベントやオンラインコミュニケーションプラットフォームに参加する際に、行動規範を遵守することを求めます。


## 報告

誰かがあなたや他の誰かを「危ない、歓迎されない」と感じさせた場合は、できるだけ早く報告してください。
匿名または個人的に報告書を作成できます。
すべての報告は、行動規範委員会によってレビューされ、機密が保持されます。

#### _電子的に_

次のリンクから匿名または非匿名のレポートを作成できます: <https://forms.gle/gEWHBWnXvZbEdFsq5>。
これは、行動規範委員会に転送される自由形式のテキストボックスです。
代わりに、行動規範委員会 (code-of-conduct@bioconductor.org) に電子メールを送信することもできます。
グループとしての行動規範委員会への報告に不安がある場合は、個々の委員会メンバーへの電子メールもしくは community-bioc Slack チャンネルでのダイレクトメッセージでも連絡できます。
可能な限り、関連するすべての電子会話のスクリーンショット・コピーを含めてください (ただ匿名性を損なう必要はありません!)。

匿名の報告を直接フォローアップすることはできませんが、完全に調査し、再発を防ぐために必要な措置を講じます。

#### _ご本人がじかに行う報告 (どのような Bioconductor のイベントでも: 直接会うまたはバーチャルで)_

イベントに出席しているイベント行動規範委員会のメンバーにご本人がじかに報告をすることができます。

個人的に報告をしてくださる場合、私達はあなたが安全に、報告を耳にされないようにすることを保証します。
ただし、あなたの報告が適切に管理されるように、他のイベントスタッフが関与する場合があるかもしれません。
安全になったら、我々はあなたに何が起こったのか教えていただくようお願いします。
これはあなたを動揺させる可能性がありますが、我々は可能な限り丁寧に対応し、誰かにあなたをサポートしてもらうようにできます。
あなたは誰かに対峙するように求められることはありませんし、我々はあなたが誰であるかを誰にも教えません。

私たちのチームは、あなたが関連のあるサポートを受けるのを喜んでお手伝いします (たとえば、ホテル・会場のセキュリティ、地域の法執行機関、地域のサポートサービスへの連絡、護衛の提供、またはイベント期間中の安全を確保するための支援等)。

私たちは、Bioconductor のイベントおよび私たちのコミュニティへのご出席と参加を大切にしています。


### 行動規範委員会

* (議長) Saskia Freytag <sas.freytag@gmail.com> (until 2023)
* Yagoub Adam <yagoub@alumni.usp.br> (until 2022)
* Leonardo Collado-Torres <lcolladotor@gmail.com> (until 2022)
* Laurent Gatto <laurent.gatto@gmail.com> (until 2023)
* Michael Love <michaelisaiahlove@gmail.com> (until 2024)
* Federico Marini <fede.maro@gmail.com> (until 2024)
* Sowmya Parthiban <sowmyaparthiban@gmail.com> (until 2024)
* Anna Quaglieri <anna.quaglieri16@gmail.com> (until 2024)
* Johannes Rainer <johannes.rainer@eurac.edu> (until 2023)
* Lluís Revilla <lluis.revilla@gmail.com> (until 2024)
* Charlotte Soneson <charlottesoneson@gmail.com> (until 2023)

[1]: https://bioc2020.bioconductor.org/code_of_conduct
