---
title: "`r emo::ji('Lithuania')` „Bioconductor“ projekto elgesio kodeksas (lietuvių, Lietuva)"
---

(Parengta pagal [„BioC 2020“ elgesio kodeksą][1])

# Elgesio kodeksas

## Versija 1.3.0 (2024 m. sausio 12 d.)

_Pradinis elgesio kodeksas, papildytas dokumentų ištraukomis iš ankstesnių konferencijų_

„Bioconductor“ bendruomenė vertina atvirą požiūrį į mokslą, kuris skatina 

* dalijimąsi idėjomis, kodu, programine įranga ir žiniomis
* bendradarbiavimą
* įvairovę ir įtrauktį
* draugišką ir svetingą aplinką
* bendruomenės indėlį

Vadovaudamasi šiomis vertybėmis, „Bioconductor“ siekia užtikrinti svetingą, palaikančią, kolegialią aplinką be priekabiavimo, bauginimo ir patyčių, nepriklausomai nuo:

* tapatybės: lyties, lytinės tapatybės ir raiškos, seksualinės orientacijos, negalios, fizinės išvaizdos, etninės priklausomybės, kūno sudėjimo, rasės, amžiaus, religijos, kalbos ir pan.
* intelektualinės pozicijos: duomenų analizės metodų pasirinkimo, programinės įrangos pasirinkimo, kodo stiliaus, mokslinių įžvalgų, karjeros etapo ir pan.

Būdami bendruomenės nariu jūs sutinkate elgtis laikydamiesi bendruomenės vertybių visuose „Bioconductor“ remiamuose renginiuose (gyvai ar virtualiai, įskaitant, bet neapsiribojant, paskaitomis, mokymais, stendinių pranešimų sesijomis, socialine veikla), elektroniniuose komunikacijos kanaluose (įskaitant, bet neapsiribojant, community-bioc [Slack kanalu](https://slack.bioconductor.org/), internetine pagalbos svetaine, internetiniais forumais, kodo paketų peržiūros svetaine ir bendravimu socialiniuose tinkluose), ar rašant bet kokius tekstus susietus su programinės įrangos paketais (įskaitant išsaugotus paketų pakeitimus).
Be to, reikalaujame, kad visi dalyviai turėtų neanonimines paskyras „Bioconductor“ interneto forumuose.
Paskyros, kurios nepaiso reikalavimo panaikinti anonimiškumą, gali būti ištrintos.

Netoleruojame priekabiavimo prie bendruomenės narių, jų bauginimo ar patyčių.
Seksualinė kalba ir vaizdai yra netinkami pristatymuose, bendraujant gyvai ar interneto svetainėse, įskaitant pokalbių kambarius.

Bet kuris asmuo, pažeidęs Elgesio kodeksą, gali būti laikinai arba visam laikui pašalintas iš elektroninės platformos ar renginio Elgesio kodekso komiteto nuožiūra.

„Bioconductor“ bendruomenė yra įsipareigojusi palaikyti etišką bendradarbiavimą, vengdama bendradarbiavimo su subjektais, kurių praktika neatitinka „Bioconductor“ vertybių.
Raginame bendruomenės narius pranešti Elgesio kodekso komitetui arba pareikšti susirūpinimą dėl bendradarbiavimo, kuris gali būti laikomas neetišku, naudojant pranešimo formą.

#### _Nepriimtino priekabiavimo, bauginimo ir patyčių elgesio pavyzdžiai_

Priekabiavimas apima, bet neapsiriboja:

* Komentarais žodinio pranešimo metu, auditorijai ar asmeniškai, kuriais menkinamas ar žeminamas kitas asmuo
* Dalijimusi seksualinio pobūdžio vaizdais internete
* Priekabiavimu fotografuojant ar įrašinėjant
* Nuolatiniu konferencijos žodinių pranešimų ar kitų renginių trukdymu
* Nepageidaujamu seksualiniu dėmesiu
* Bet kurio iš aukščiau nurodytų veiksmų propagavimu ar skatinimu

Bauginimas ir patyčios apima, bet neapsiriboja:

* Agresyviu ar užgauliu elgesiu 
* Tyčiojimusi ar šaipymusi iš kito asmens intelekto, darbo, požiūrio, užduoto klausimo ar išsakyto komentaro
* Argumentais nukreiptais į kieno nors lytį, lytinę tapatybę ir raišką, seksualinę orientaciją, negalią, fizinę išvaizdą, kūno sudėjimą, rasę, amžių, religiją ar kitas asmenines savybes mokslinės diskusijos kontekste
* Tyčiniu vertimu kitą asmenį jaustis nepageidaujamu
* Trolinimu (tyčia kurstančios ar įžeidžiančios žinutės)
* Nuolatiniais pranešimais, kurie nesusiję su pokalbio tema

## Kodekso taikymas

Tikimasi, kad bet kuris asmuo, kurio bus prašoma nutraukti priekabiavimą ar bauginantį elgesį, nedelsdamas paklus.

Jei asmuo pažeidžia Elgesio kodeksą, Elgesio kodekso komitetas pasilieka teisę imtis bet kokių veiksmų, kurie užtikrintų svetingą aplinką visiems bendruomenės nariams. Tai apima įspėjimą įtariamam pažeidėjui arba laikiną ar nuolatinį pašalinimą iš renginio ir/arba elektroninių platformų, kurias valdo „Bioconductor“.

Elgesio kodekso komitetas gali imtis veiksmų, kad ištaisytų susidariusią situaciją dėl bet ko, kuo siekiama sutrikdyti renginį ar elektroninio bendravimo platformą arba paversti aplinką priešišką bet kuriam bendruomenės nariui.

Tikimės, kad visi „Bioconductor“ bendruomenės nariai laikysis elgesio kodekso dalyvaudami „Bioconductor“ renginiuose ir elektroninėse bendravimo platformose.

## Pranešimas apie pažeidimus

Jei kas nors verčia jus ar kitus asmenis jaustis nesaugiai ar nepageidaujamai, praneškite apie tai kuo greičiau. Pranešimą galite pateikti anonimiškai arba asmeniškai. Visus pranešimus peržiūrės Elgesio kodekso komitetas ir jie bus konfidencialūs.

#### _Pranešimas elektroniniu būdu_

Anoniminį arba neanoniminį pranešimą galite pateikti naudodami šią nuorodą: https://forms.gle/gEWHBWnXvZbEdFsq5. Laisvo teksto lauke užrašytas pranešimas bus perduotas Elgesio kodekso komitetui. Taip pat galite Elgesio kodekso komitetui rašyti el. paštu (code-of-conduct@bioconductor.org). Jei jaučiatės nepatogiai rašydami Elgesio kodekso komitetui kaip grupei, galite susisiekti su bet kuriuo komiteto nariu el. paštu arba tiesiogine žinute community-bioc Slack kanale. Jeigu tik įmanoma, pridėkite visų susijusių elektroninių pokalbių ekrano nuotraukas arba kopijas (tai darant jums nereikia pažeisti savo anonimiškumo!).

Mes negalime su jumis susisiekti tiesiogiai dėl anoniminio pranešimo, tačiau visapusiškai jį ištirsime ir imsimės visų būtinų veiksmų, kad žalingi veiksmai nepasikartotų.

#### _Pranešimas asmeniškai (tinka visiems „Bioconductor“ renginiams: vykstantiems gyvai ar virtualiai)_

Asmeninį pranešimą galite pateikti bet kuriam renginyje dalyvaujančiam Elgesio kodekso komiteto nariui. 

Priimdami asmeninį pranešimą, užtikrinsime, kad esate saugūs ir jūsų neišgirs pašaliniai asmenys. Galime įtraukti kitus renginio darbuotojus, kad užtikrintume tinkamą jūsų pranešimo tvarkymą. Kai būsite saugūs, paprašysime jūsų papasakoti, kas nutiko. Tai gali jus nuliūdinti, bet mes su jumis elgsimės kuo pagarbiau, be to, galite atsivesti žmogų, kuris jus palaikys. Jūsų nebus prašoma stoti akis į akį su bet kokiu kitu asmeniu ir mes niekam neatskleisime, kas jūs esate.

Mūsų komanda mielai padės jums gauti reikiamą pagalbą (pvz., padės susisiekti su viešbučio ar susirinkimų vietos apsauga, vietos teisėsaugos institucijomis, vietos pagalbos tarnybomis, suteiks palydą ar kitaip padės jums jaustis saugiai renginio metu).

Vertiname jūsų dalyvavimą „Bioconductor“ renginiuose ir mūsų bendruomenės veikloje.

#### _Ombudsmenas_

Suprantame, kad galite pageidauti, jog konflikto sprendimą prižiūrintis asmuo būtų nesusijęs su „Bioconductor“. Siekdamas tai palengvinti, Elgesio kodekso komitetas paskirs ombudsmeną iš kitos atvirojo kodo bendruomenės nei „Bioconductor“. Nors ombudsmenas neturi įgaliojimų nustatyti, pakeisti ar panaikinti Elgesio kodekso komiteto priimtų sprendimų, jis gali padėti bendruomenės nariams teikdamas patarimus, tarpininkaudamas, instruktuodamas ir nukreipdamas į kitus išteklius. Siekiant užtikrinti konfidencialų, nešališką, neformalų ir nepriklausomą procesą, su ombudsmenu galima susisiekti tiesiogiai el. paštu (žr. toliau). 

#### _Konfliktų sprendimo procedūra_

Elgesio kodekso komitetas taiko standartinę konfliktų sprendimo procedūrą. 
Ši procedūra yra apibendrinta [čia](https://bioconductor.github.io/CodeOfConduct/incident_response.html). Konfliktų sprendimo procedūra yra pagrįsta knyga „Kaip reaguoti į elgesio kodekso pranešimus“, kurios autoriai yra Valerie Aurora ir Mary Gardiner.


### Elgesio kodekso komitetas 

* (Vienas iš pirmininkų) Anna Quaglieri anna.quaglieri16@gmail.com (iki 2024 m.) ji/jos [EN, IT]
* (Vienas iš pirmininkų) Gerry Tonkin-Hill g.tonkinhill@gmail.com (iki 2025 m.) jis/jo [EN]
* Martín Dávila-Cervantes aldntmi@gmail.com (iki 2025 m.) jis/jo [EN, FR, ES] 
* Federica Gazzelloni fede.gazzelloni@gmail.com (iki 2025 m.) ji/jos [IT, EN]
* Michael Love michaelisaiahlove@gmail.com (iki 2024 m.) jis/jo [EN] (TAB)
* Federico Marini fede.maro@gmail.com (iki 2024 m.) jis/jo [EN, IT, DE]
* Sowmya Parthiban sowmyaparthiban@gmail.com (iki 2024 m.) ji/jos [EN, Tamil]
* Shixiang Wang wangshx@shanghaitech.edu.cn (iki 2025 m.) jis/jo [CN, EN]
* Lluís Revilla lluis.revilla@gmail.com (iki 2024 m.) jis/jo [CAT, ES, EN]
* Kevin Rue-Albrecht kevinrue67@gmail.com  (iki 2024 m.) jis/jo [FR, EN] (CAB)
* Paulina Boadiwaa Mensah pabbyboadiwaa@gmail.com (iki 2025 m.) ji/jos [EN, Akan]
* Peace Sandy peacesandy04@gmail.com ji/jos (iki 2025 m.) [EN]
* Sinmisoluwa Adesanya adesanyasinmisoluwa@gmail.com ji/jos (iki 2025 m.) [EN, Yoruba]
* (Ombudsmenas) Michelle Savage michellesavage.galaxy@gmail.com (projektas „Galaxy“) ji/jos [ES, EN]

[1]: https://bioc2020.bioconductor.org/code_of_conduct
