---
title: "`r paste(emo::ji('Belgium'), emo::ji('Netherlands'))` Gedragscode voor het Bioconductor project (Nederlands; België/Nederland)"
---

(Aangepast van de [Gedragscode voor het BioC 2020 congres][1], vertaald uit het [Engels](en-US.html)).

# Gedragscode

## Versie 1.3.0 (12 januari, 2024)

_Initiële gedragscode, uitbreiding van voorgaande congres-specifieke documenten_

De Bioconductor gemeenschap waardeert een open benadering tot wetenschap die de volgende waarden nastreeft:

* het delen van ideeën, code, software en expertise
* samenwerking
* diversiteit en inclusiviteit
* een vriendelijke en gastvrije omgeving
* bijdragen door de gemeenschap

In lijn met deze waarden zet Bioconductor zich in om een gastvrije, ondersteunende, collegiale ervaring te bieden zonder intimidatie, bedreiging en pesten, ongeacht:

* identiteit: geslacht, genderidentiteit en -expressie, seksuele geaardheid, handicap, uiterlijk, etniciteit, lichaamsgrootte, ras, leeftijd, religie, taal, enz.
* intellectuele positie: benaderingen van data-analyse, software-voorkeuren, codeerstijl, wetenschappelijk perspectief, loopbaanfase, enz.

Door deel te nemen aan deze gemeenschap stemt u ermee in zich niet in te laten met gedrag dat in strijd is met deze waarden tijdens een door Bioconductor gesponsord evenement (persoonlijk of virtueel, inclusief maar niet beperkt tot lezingen, workshops, postersessies, sociale activiteiten), elektronische communicatiekanalen ( inclusief maar niet beperkt tot de "community-bioc" [Slack](https://slack.bioconductor.org), de ondersteuningssite, online forums, de beoordelingssite voor packages en communicatie via sociale media), of packages (commits inbegrepen). 

Verder eisen we dat alle deelnemers identificeerbare accounts hebben op de online fora van Bioconductor. Accounts die zich hier niet aan houden na verzoek tot de-anonimisering kunnen worden verwijderd.

We tolereren geen intimidatie of pesterijen van leden van de gemeenschap. Seksuele taal en beelden zijn niet gepast in presentaties, communicatie of op online locaties, inclusief chats.

Elke persoon/personen die de Gedragscode overtreedt, kan naar goeddunken van de Gedragscodecommissie worden bestraft of tijdelijk of permanent worden verwijderd van een elektronisch platform of evenement.

De Bioconductor gemeenschap zet zich in voor ethische partnerschappen en vermijdt partnerschappen met entiteiten waarvan de praktijken niet in overeenstemming zijn met de waarden van Bioconductor.
Wij moedigen leden van de gemeenschap aan om hun zorgen over partnerschappen die zij onethisch achten te melden bij de gedragscodecommissie via het meldingsformulier.

#### _Voorbeelden van onaanvaardbare intimidatie en pestgedrag_

Intimidatie omvat, maar is niet beperkt tot:

* Opmerkingen maken in chats, voor een publiek of persoonlijk, die een andere persoon kleineren of vernederen
* Online seksuele afbeeldingen delen
* Intimiderend fotograferen of opnemen
* Aanhoudende verstoring van gesprekken of andere evenementen
* Ongewenste seksuele aandacht
* Pleiten voor, of aanmoedigen van, een van de bovenstaande gedragingen

Bedreiging en pesten omvatten, maar zijn niet beperkt tot:

* Agressief of brutaal gedrag
* Het bespotten of beledigen van iemands intellect, werk, perspectief of vraag/opmerking
* Verwijzen naar iemands geslacht, genderidentiteit en -expressie, seksuele geaardheid, handicap, fysieke verschijning, lichaamsgrootte, ras, leeftijd, religie of andere persoonlijke kenmerken in de context van een wetenschappelijke discussie
* Iemand opzettelijk onwelkom laten voelen
* "Trolling" gedrag (opzettelijk opruiende of beledigende berichten)
* Aanhoudende off-topic berichten

## Handhaving

Iedereen die wordt gevraagd om te stoppen met intimiderend of pestend gedrag, wordt geacht dit onmiddellijk te doen.

Als een persoon de Gedragscode schendt, behoudt de Gedragscodecommissie zich het recht om elke actie te ondernemen die zorgt voor een gastvrije omgeving voor alle leden van de gemeenschap. Dit omvat het waarschuwen van de vermeende overtreder of tijdelijke/permanente verwijdering van het evenement en/of elektronische platforms onder controle van Bioconductor.

De gedragscodecommissie kan actie ondernemen om alles dat is ontworpen om, of met de duidelijke impact van, het verstoren van een evenement of elektronisch communicatieplatform of het vijandig maken van de omgeving voor een lid van de gemeenschap recht te zetten .

We verwachten dat iedereen in de Bioconductor-gemeenschap de Gedragscode naleeft bij deelname aan Bioconductor-evenementen en online communicatieplatforms.

## Aangifte

Als iemand u of iemand anders een onveilig of onwelkom gevoel geeft, meld dit dan zo snel mogelijk. U kunt zowel anoniem als persoonlijk een melding doen. Alle meldingen worden beoordeeld door de Gedragscodecommissie en vertrouwelijk behandeld.

#### _Elektronisch_

U kunt een anonieme of niet-anonieme melding doen via de volgende link: https://forms.gle/gEWHBWnXvZbEdFsq5. Dit is een vrije tekstbox die wordt doorgestuurd naar de Gedragscodecommissie. U kunt ook een e-mail sturen naar de Gedragscodecommissie (code-of-conduct@bioconductor.org). Als u zich niet op uw gemak voelt om aan de Gedragscodecommissie als groep te rapporteren, kunt u contact opnemen met elk individueel commissielid via e-mail of een direct bericht op het "community-bioc" Slack-kanaal. Voeg indien mogelijk screenshots/kopieën van alle relevante elektronische gesprekken toe (u hoeft uw anonimiteit niet in gevaar te brengen!).

We kunnen een anonieme melding niet rechtstreeks met u opnemen, maar we zullen deze volledig onderzoeken en alle nodige maatregelen nemen om herhaling te voorkomen.

#### _Persoonlijk rapport (voor alle Bioconductor-evenementen: persoonlijk of virtueel)_

U kunt een persoonlijke melding doen bij elk lid van de gedragscodecommissie dat aanwezig is op een evenement.

Bij een persoonlijke melding zorgen wij ervoor dat u veilig bent en niet kunt worden afgeluisterd. We kunnen andere evenementenmedewerkers inschakelen om ervoor te zorgen dat uw melding op de juiste manier wordt beheerd. Als het veilig is, vragen we u om ons te vertellen wat er is gebeurd. Dit kan verontrustend zijn, maar we gaan er zo respectvol mogelijk mee om en u kunt iemand meenemen om u te ondersteunen. U wordt niet gevraagd om iemand te confronteren, en we zullen niemand vertellen wie u bent.

Ons team helpt u graag om de relevante ondersteuning te krijgen (bijvoorbeeld hulp bij het contacteren van hotel-/locatiebeveiliging, lokale wetshandhaving, lokale ondersteuningsdiensten, het bieden van escortes of anderszins helpen om u veilig te voelen gedurende de duur van het evenement).

We waarderen uw aanwezigheid en deelname aan Bioconductor-evenementen en in onze gemeenschap.

#### _Ombudspersoon_

We begrijpen dat u misschien wilt dat een persoon die geen relatie heeft met Bioconductor toezicht houdt op uw conflictoplossing. Om dit te faciliteren zal de Gedragscodecommissie een ombudspersoon aanstellen uit een andere open source community dan leden van het Bioconductor-project. Hoewel ze niet de bevoegdheid hebben om besluiten van de Gedragscodecommissie vast te stellen, te wijzigen of opzij te zetten, kunnen ze leden van de gemeenschap helpen door advies, bemiddeling, coaching en doorverwijzing naar andere
bronnen. De ombudspersoon is rechtstreeks bereikbaar via e-mail (zie hieronder) om te
zorgen voor een vertrouwelijk, onpartijdig, informeel en onafhankelijk proces.

#### _Incident procedure_

De Gedragscodecommissie volgt een standaardprocedure voor het omgaan met conflicten.
Deze procedure wordt [hier](https://bioconductor.github.io/CodeOfConduct/incident_response.html) kort samengevat.
Deze procedure is gebaseerd op het boek "How to Respond to Code of Conduct Reports" van Valerie Aurora en Mary Gardiner.

### Gedragscodecommissie

* (Co-voorzitter) Anna Quaglieri anna.quaglieri16@gmail.com (tot 2024) zij/haar [EN, IT]
* (Co-voorzitter) Gerry Tonkin-Hill g.tonkinhill@gmail.com (tot 2025) hij/hem [EN]
* Martín Dávila-Cervantes aldntmi@gmail.com (tot 2025) hij/hem [EN, FR, ES] 
* Federica Gazzelloni fede.gazzelloni@gmail.com (tot 2025) zij/haar [IT,EN]
* Gerry Tonkin-Hill g.tonkinhill@gmail.com (tot 2025) hij/hem [EN] 
* Michael Love michaelisaiahlove@gmail.com (tot 2024) hij/hem [EN] (TAB)
* Federico Marini fede.maro@gmail.com (tot 2024) hij/hem [EN, IT, DE]
* Sowmya Parthiban sowmyaparthiban@gmail.com (tot 2024) zij/haar [EN, Tamil]
* Anna Quaglieri anna.quaglieri16@gmail.com (tot 2024) zij/haar [EN, IT]
* Lluís Revilla lluis.revilla@gmail.com (tot 2024) hij/hem [CAT, ES, EN]
* Kevin Rue-Albrecht kevinrue67@gmail.com (tot 2024) hij/hem [FR, EN] (CAB)
* (Ombudspersoon) Michelle Savage michellesavage.galaxy@gmail.com (Galaxy-project) zij/haar [ES,EN]

[1]: https://bioc2020.bioconductor.org/code_of_conduct
