---
title: "`r emo::ji('Russia')` Кодекс поведения проекта Bioconductor (Russian, Russian Federation)"
---

(Адаптировано из [Кодекса поведения BIOC 2020][1])

# Кодекс поведения

## Версия 1.2.0 (24 ноября 2022 г.)

_Первоначальный Кодекс поведения, дополненный выдержками из документов из предыдущих конференций_

Члены проекта Bioconductor поддерживают открытый подход к науке которая способствует:

* обмену идеями, кодом, программным обеспечением и опытом
* совместной работе
* разнообразию и инклюзивности
* доброй и гостеприимной обстановке
* участию членов проекта

В соответствии с этими ценностями, Bioconductor стремится обеспечить гостеприимную, поддерживающую, коллегиальную атмосферу, свободную от преследований, запугивания и издевательств, независимо от:

* идентичность: пол, гендерное самовыражение, сексуальная ориентация, ограниченные возможности, внешний вид, этническая принадлежность, размер тела, раса, возраст, религия, язык/акцент, и т.д.
* интеллектуальная позиция: подходы к анализу данных, предпочтения программного обеспечения, стиль программирования, научная перспектива, этап карьеры, и т.д.

Как участник проекта Bioconductor, вы соглашаетесь поддерживать этот стиль поведения и взаимоотношений на любом мероприятии, спонсируемом Bioconductor (лично или виртуально, включая, но не ограничиваясь, беседами, семинарами, постерными сессиями, социальными мероприятиями), в электронных каналах связи (включая, но не ограничиваясь, [community-bioc Slack канал](https://slack.bioconductor.org/), сайт поддержки, онлайн-форумы, сайт тестирования библиотек, и общение в социальных сетях), и в коде библиотек (включая коммиты на GitHub). Также, мы требуем использование реальной информации в аккаунтах Bioconductor. Аккаунты противоречащие этим правилам и игнорирующие требования использования реальных идентификационных данных будут удалены.

Мы не терпим притеснений, запугивания или издевательств над членами проекта. Запрещены сексуальные выражения и образы в презентациях, личном или онлайн общении, включая чаты.

Любое лицо/лица, нарушающие этот Кодекс поведения, могут быть подвергнуты санкциям или временно или навсегда удалены с электронной платформы или мероприятия по усмотрению Комитета по Кодексу поведения.


#### Примеры неприемлемого преследования, запугивания и издевательств

Преследование включает, но не ограничивается:

* Комментарии в чатах, для аудитории или лично, которые унижают другого человека
* Обмен сексуальными изображениями
* Раздражающие фотографии или записи
* Постоянное прерывание переговоров или других мероприятий
* Нежелательное сексуальное внимание
* Пропагандирование или поощрение любых из вышеперечисленных действий

Запугивание и издевательства включают, но не ограничиваются:

* Агрессивное или надменное поведение
* Насмешка или оскорбление интеллекта, работы, точки зрения другого человека или вопроса/комментария
* Упоминание чьего-либо пола, гендерной идентичности и самовыражения, сексуальной ориентации, инвалидности, физического облика, размера тела, расы, возраста, религии или других личных качеств в контексте научной дискуссии
* Намеренное создание атмосферы враждебности
* Троллинг (намеренное подстрекательство к оскорбительным сообщениям)
* Постоянные сообщения не по теме


### Обеспечение исполнения Кодекса

Ожидается, что любой, кого попросят прекратить беспокоящее или запугивающее поведение, должен немедленно подчинится.

Если какое-либо лицо/лица нарушают Кодекс поведения, Комитет по Кодексу поведения оставляет за собой право предпринять любые действия, которые обеспечат благоприятную обстановку для всех членов проекта. Это включает предупреждение предполагаемому нарушителю или временное/постоянное исключение с мероприятия и/или электронных платформ, находящихся под контролем Bioconductor.

Комитет по кодексу поведения может принять меры для исправления действий, нарушающих мероприятия или электронную коммуникационную платформу или направленных на создание неблагоприятной и враждебной атмосферы для любого члена сообщества.

Мы ожидаем, что все члены проекта Bioconductor будут соблюдать Кодекс поведения при участии в мероприятиях Bioconductor и на платформах онлайн-коммуникации.


## Отчетность

Если кто-то заставляет Вас или кого-либо еще чувствовать себя небезопасно или некомфортно, пожалуйста, сообщите об этом как можно скорее. Вы можете сделать отчет анонимно или лично. Все отчеты будут рассмотрены Комитетом по кодексу поведения и будут храниться в тайне.

#### В электронном виде

Вы можете сделать анонимный или неанонимный отчет по следующей ссылке:
https://forms.gle/gEWHBWnXvZbEdFsq5. Эта форма позволит написать отчёт в свободной форме и отправить его в Комитет по кодексу поведения. В качестве альтернативы вы можете отправить электронное письмо Комитету по кодексу поведения (code-of-conduct@bioconductor.org). Если вам неудобно посылать отчёт комитету по Кодексу поведения, вы можете связаться с любым отдельным членом комитета по электронной почте или прямым сообщением по Slack каналу community-bioc. Пожалуйста, по возможности включайте скриншоты/копии всех соответствующих электронных разговоров (Вы можете анонимизировать своё имя).

Мы не сможем напрямую связаться с Вами по поводу анонимного отчёта, но мы полностью расследуем его и предпримем все необходимые действия, чтобы предотвратить повторение.

#### _Личное сообщение (для любых событий Bioconductor: лично или виртуально)_

Вы можете сделать личный отчет любому члену комитета по Кодексу поведения, присутствующему на мероприятии.

При составлении личного отчета мы позаботимся о том, чтобы Вы были в безопасности и Вас никто не мог подслушать. Мы можем привлечь других сотрудников для проведения мероприятий, чтобы обеспечить надлежащее управление Вашим отчетом. Удостоверившись в безопасности, мы попросим Вас рассказать нам о том, что произошло. Это может быть неприятно, но мы отнесемся к этому как можно более уважительно, и Вы можете привести кого-нибудь, кто поддержит вас. Вас не попросят встречаться с оскорбителем лицом к лицу, и мы сохраним Вашу анонимность.

Наша команда будет рада оказать Вам соответствующую поддержку (например, помочь связаться с охраной отеля/места проведения, местными правоохранительными органами, местными службами поддержки, предоставить сопровождение или иным образом помочь Вам чувствовать себя в безопасности на протяжении всего мероприятия).

Мы ценим Ваше участие в мероприятиях Bioconductor и в нашем сообществе.

#### _Омбудсмен_

Мы понимаем, что вы можете захотеть, чтобы человек, не связанный с Bioconductor, наблюдал за разрешением вашего конфликта. Чтобы облегчить это, Комитет по Кодексу поведения назначит омбудсмена из сообщества открытого исходного кода, отличного от участников проекта Bioconductor. Хотя они не имеют полномочий устанавливать, изменять или отменять решения, принятые Комитетом по Кодексу поведения, они могут помогать членам сообщества, предлагая консультации, посредничество, обучение и направления к другим ресурсам. С омбудсменом можно связаться напрямую по электронной почте (см. ниже), чтобы обеспечить конфиденциальный, беспристрастный, неформальный и независимый процесс.

#### _Процедура инцидента_

Комитет по Кодексу поведения следует стандартной процедуре разрешения конфликтов.
Эта процедура кратко описана [здесь](https://bioconductor.github.io/CodeOfConduct/incident_response.html). Инцидентные процедуры основаны на книге "Как реагировать на сообщения о кодексе поведения" написанной Валерией Аврора и Мэри Гардинер.

### Комитет по Кодексу поведения

* (Chair) Saskia Freytag sas.freytag@gmail.com (до 2023) she/her [EN, DE]
* Laurent Gatto laurent.gatto@gmail.com (до 2023) he/him [FR, EN] (TAB, European Bioconductor Society)
* Martín Dávila-Cervantes aldntmi@gmail.com (до 2025) he/him [EN, FR, ES] 
* Federica Gazzelloni fede.gazzelloni@gmail.com (до 2025) she/her [IT,EN]
* Gerry Tonkin-Hill g.tonkinhill@gmail.com (до 2025) he/him [EN] 
* Michael Love michaelisaiahlove@gmail.com (до 2024) he/him [EN] (TAB)
* Federico Marini fede.maro@gmail.com (до 2024) he/him [EN, IT, DE]
* Sowmya Parthiban sowmyaparthiban@gmail.com (до 2024) she/her [EN, Tamil]
* Shixiang Wang wangshx@shanghaitech.edu.cn (до 2025) he/him [CN,EN]
* Anna Quaglieri anna.quaglieri16@gmail.com (до 2024) she/her [EN, IT]
* Lluís Revilla lluis.revilla@gmail.com (до 2024) he/him [CAT, ES, EN]
* Kevin Rue-Albrecht kevinrue67@gmail.com  (до 2024) he/him [FR, EN] (CAB)
* (Ombudsperson) Michelle Savage michellesavage.galaxy@gmail.com (Galaxy project) she/her [ES,EN]

[1]: https://bioc2020.bioconductor.org/code_of_conduct