---
title: "`r emo::ji('China')` Project-wide Code of Conduct statement for Bioconductor (Chinese, China)"
---

(改编自[BioC 2020行为准则][1]，翻译自[英语版](en-US.html) )

# 行为准则

## 1.2.0 版本（2022 年 11 月 25 日）

_此为初步的项目范围行为准则，扩展自先前的特定会议文件_


Bioconductor 社区重视以开放的科学方法促进

* 思想、代码、软件和专业知识的共享
* 合作
* 多元性和包容性
* 友善和热情的环境
* 社区贡献

根据这些价值观，Bioconductor致力于提供欢迎、支持、合作且免于骚扰、恐吓或欺凌的体验，无论你的：

* 身份：性别、性别认同和表达、性取向、残疾、外貌、种族、体型、人种、年龄、宗教信仰、语言等。
* 知识立场：数据分析方式、软件偏好、代码风格、科学观点、事业阶段等。

参与此社区，即表示您同意在任何 Bioconductor 赞助的活动（线下或虚拟，包括但不限于讲座、研讨会、海报会议、社交活动）或电子通信渠道（包括但不限于 [community-bioc Slack](https://slack.bioconductor.org/)、支持网站、在线论坛、软件包审查网站和社交媒体通讯）中均不从事违反这些价值观的行为。
此外，我们要求所有参与者在 Bioconductor 在线论坛中使用身份可识别的帐户名。在要求去匿名化后不遵守此规定的帐户可能会被删除。
 
我们不容忍对社区成员的骚扰、恐吓或欺凌。
色情文字和图像不宜出现于演讲、交流与线上场所，包括聊天。
 
根据行为准则委员会的判断，任何违反行为准则的人都可能被暂时制裁或永久地驱逐出电子平台或活动。


### _不可接受的骚扰、恐吓和欺凌行为的示例_

骚扰包括但不限于：

* 在聊天中向公众或个人发表贬低或侮辱他人的评论
* 在线分享色情图片
* 骚扰摄影或录音
* 持续扰乱讲座或其他活动
* 不受欢迎的性关注
* 提倡或鼓励上述任何行为

恐吓和欺凌包括但不限于:

* 攻击性或威胁行为
* 嘲笑或侮辱他人的智力、工作、观点或问题/评论
* 在科学讨论中提及某人的性别、性别认同和表达、性取向、残疾、外貌、体型、种族、年龄、宗教信仰或其他个人属性
* 故意排挤冷落某人
* 钓鱼行为（故意煽风点火或引起冒犯）
* 持续性偏离主题的帖子


## 执行

任何人当被要求停止骚扰或恐吓行为时都应立即遵守。
 
当有人违反行为准则时，行为准则委员会保留采取任何行动以确保为所有社区成员提供友好环境的权利。
这包括警告被指控者或将其暂时或永久移出 Bioconductor 控制下的活动和/或电子平台。
 
行为准则委员会可能会采取行动纠正任何旨在扰乱活动或电子通信平台或使环境对任何社区成员不利或具有明显影响的行为。
 
我们希望 Bioconductor 社区的每个人在参与 Bioconductor 活动和在线交流平台时都能遵守行为准则。


## 报告

如果有人让您或其他任何人感到不安全或不受欢迎，请尽快举报。
您可以选择匿名或个人举报。
所有报告将由行为准则委员会审查并予以保密。

#### _电子方式_

您可以通过以下链接进行匿名或非匿名举报：<https://forms.gle/gEWHBWnXvZbEdFsq5>。
这是一个自由格式的文本框，填写的内容会被转发给行为准则委员会。
或者，您也可以向行为准则委员会发送电子邮件 （code-of-conduct@bioconductor.org）。
如果您不希望将事件报告给作为团体的整个行为准则委员会，您也可以通过电子邮件或 Slack 群组 community-bioc 的私信功能直接联系任意一位委员会成员。
请尽可能提供所有相关电子对话的屏幕截图/副本（您的匿名性不会受影响！）。
 
我们无法直接向您跟进匿名举报，但我们会对其进行全面调查并采取一切必要措施防止其再次发生。

#### _个人举报（针对任何线下或虚拟举办的 Bioconductor 活动）_

您可以直接向出席活动的行为准则委员会的任何成员进行个人举报。
 
在进行个人举报时，我们将确保您是安全的且不会被偷听。
其他的活动工作人员可能会参与其中以确保妥善管理您的报告。
在安全的情况下，我们将请您告诉我们发生了什么。
这可能会让您感到不安，但我们会尽可能以尊重的方式处理，您也可以找人陪同并支持您。
您不会被要求与任何人对质，我们也不会告诉任何人您是谁。
 
我们的团队将很乐意协助您获得相关支持（例如，帮助联系酒店或场地安保人员、当地执法部门、当地支持服务、提供护送或以其他方式帮助您在活动期间感到安全）。
 
我们重视您出席 Bioconductor 活动和参与我们的社区。

#### _监察员_

我们理解您可能希望有一名与 Bioconductor 无关的人监督您的冲突解决过程。为了便于此事，行为准则委员会将从与 Bioconductor 项目成员不同的开源社区中任命一名监察员。尽管监察员无权制定、修改或撤销行为准则委员会做出的决定，但他们可以通过提供咨询、调解、辅导和引荐其他资源来协助社区成员。监察员可以直接通过电子邮件联系（见下文），以确保保密、公正、非正式和独立的过程。

#### _事件处理程序_

行为准则委员会按照标准程序处理冲突。该程序在[这里](https://bioconductor.github.io/CodeOfConduct/incident_response.html)被简要概括。事件处理程序基于 Valerie Aurora 和 Mary Gardiner 的书籍《如何回应行为准则报告》。


### 行为准则委员会

* （主席）Saskia Freytag <sas.freytag@gmail.com>（至2023年）
* Laurent Gatto <laurent.gatto@gmail.com>（至2023年）
* Martín Dávila-Cervantes aldntmi@gmail.com（至2025年）
* Federica Gazzelloni fede.gazzelloni@gmail.com（至2025年）
* Gerry Tonkin-Hill g.tonkinhill@gmail.com（至2025年）
* Michael Love michaelisaiahlove@gmail.com（至2024年）
* Federico Marini fede.maro@gmail.com（至2024年）
* Sowmya Parthiban sowmyaparthiban@gmail.com（至2024年）
* Shixiang Wang wangshx@shanghaitech.edu.cn（至2025年）
* Anna Quaglieri anna.quaglieri16@gmail.com（至2024年）
* Lluís Revilla lluis.revilla@gmail.com（至2024年）
* Kevin Rue-Albrecht kevinrue67@gmail.com（至2024年）
* （监察员）Michelle Savage michellesavage.galaxy@gmail.com (Galaxy 项目)

[1]: https://bioc2020.bioconductor.org/code_of_conduct